version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
  
  inference:
    build:
      context: .
      dockerfile: src/inference/Dockerfile
    volumes:
      - ./logs:/app/logs
    
  mlflow:
    image: mlflow/mlflow:latest
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=mysql://root:password@mlflow-db/mlflow
    volumes:
      - ./mlflow:/mlflow
    depends_on:
      - mlflow-db
  
  mlflow-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mlflow
    volumes:
      - mlflow_db_data:/var/lib/mysql

volumes:
  grafana_data:
  mlflow_db_data:
