version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - ${GRAFANA_PORT}:${GRAFANA_PORT}
    volumes:
      - grafana_data:/var/lib/grafana
      - log_data:/var/lib/grafana/logs
      - ./grafana.ini:/etc/grafana/grafana.ini
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_SERVER_HTTP_PORT: ${GRAFANA_PORT}
    depends_on:
      - influxdb

  inference:
    build:
      context: .
      dockerfile: src/inference/Dockerfile
    volumes:
      - log_data:/app/logs
    ports:
      - ${INFERENCE_PORT}:${INFERENCE_PORT}
    environment:
      - S3_PORT=${S3_PORT}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - BUCKET_NAME=${BUCKET_NAME}
      - MLFLOW_PORT=${MLFLOW_PORT}
      - INFLUX_PORT=8086
      - INFLUX_ORG=${INFLUX_ORG}
      - INFLUX_DATABASE=${INFLUX_DATABASE}
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - INFERENCE_PORT=${INFERENCE_PORT}
    depends_on:
      - mlflow
      - minio
      - influxdb

  mlflow:
    build:
      context: .
      dockerfile: src/mlflow/Dockerfile
    ports:
      - "${MLFLOW_PORT}:${MLFLOW_PORT}"
    environment:
      MLFLOW_PORT: ${MLFLOW_PORT}
      MLFLOW_TRACKING_URI: mysql+pymysql://mlflow:mlflow@mysql:3306/mlflow
      MLFLOW_S3_ENDPOINT_URL: http://minio:${S3_PORT}
      AWS_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
    depends_on:
      - mysql
      - minio

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mlflowadminpassword
      MYSQL_DATABASE: mlflow
      MYSQL_USER: mlflow
      MYSQL_PASSWORD: mlflow
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  minio:
    image: minio/minio:latest
    ports:
      - ${S3_PORT}:${S3_PORT}
      - ${MINIO_UI_PORT}:${MINIO_UI_PORT}
    environment:
      MINIO_ACCESS_KEY: ${S3_ACCESS_KEY_ID}
      MINIO_SECRET_KEY: ${S3_SECRET_ACCESS_KEY}
    command: server /data --console-address :${MINIO_UI_PORT}
    volumes:
      - minio_data:/data

  influxdb:
    image: influxdb:latest
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUX_ADMIN_USER}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUX_ADMIN_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUX_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUX_DATABASE}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUX_TOKEN}
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2


volumes:
  log_data:
  grafana_data:
  mysql_data:
  minio_data:
  influxdb_data:
  influxdb_config:
