version: '3.8'

services:
  inference:
    build:
      context: .
      dockerfile: src/inference/Dockerfile
    volumes:
      - log_data:/app/logs
    ports:
      - "5001:5000"

volumes:
  log_data:
