version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

  inference:
    build:
      context: .
      dockerfile: src/inference/Dockerfile
    volumes:
      - log_data:/app/logs
    ports:
      - "5001:5000"

volumes:
  log_data:
  grafana_data:
