version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - ${GRAFANA_PORT}:${GRAFANA_PORT}
    volumes:
      - grafana_data:/var/lib/grafana
      - log_data:/var/lib/grafana/logs
      - ./src/grafana//grafana.db:/var/lib/grafana/grafana.db
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_SERVER_HTTP_PORT: ${GRAFANA_PORT}
    depends_on:
      - influxdb

  inference:
    build:
      context: .
      dockerfile: src/inference/Dockerfile
    volumes:
      - log_data:/app/logs
    ports:
      - ${INFERENCE_PORT}:${INFERENCE_PORT}
    environment:
      - S3_PORT=${S3_PORT}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - BUCKET_NAME=${BUCKET_NAME}
      - MLFLOW_PORT=${MLFLOW_PORT}
      - MLFLOW_S3_ENDPOINT_URL=http://minio:${S3_PORT}
      - INFLUX_PORT=8086
      - INFLUX_ORG=${INFLUX_ORG}
      - INFLUX_DATABASE=${INFLUX_DATABASE}
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - INFERENCE_PORT=${INFERENCE_PORT}
      - MODEL_TRAINING_PORT=${MODEL_TRAINING_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_USER_PASSWORD=${MYSQL_USER_PASSWORD}
      - CONFIG_DATABASE=${CONFIG_DATABASE}
      - LOGFILE_NAME=${INFERENCE_LOGFILE_NAME}
      - EMAIL_SMTP_SERVER=${EMAIL_SMTP_SERVER}
      - EMAIL_SMTP_PORT=${EMAIL_SMTP_PORT}
      - EMAIL_SMTP_USER=${EMAIL_SMTP_USER}
      - EMAIL_SMTP_PASSWORD=${EMAIL_SMTP_PASSWORD}
      - EMAIL_RECIPIENT=${EMAIL_RECIPIENT}
      - DAGSTER_PORT=${DAGSTER_PORT}
    depends_on:
      - minio
      - influxdb
      - mysql

  config_ui:
    build:
      context: .
      dockerfile: src/config_ui/Dockerfile
    ports:
      - ${CONFIG_UI_PORT}:${CONFIG_UI_PORT}
    environment:
      - INFERENCE_PORT=${INFERENCE_PORT}
      - MODEL_TRAINING_PORT=${MODEL_TRAINING_PORT}
    depends_on:
      - inference

  mlflow:
    build:
      context: .
      dockerfile: src/mlflow/Dockerfile
    ports:
      - "${MLFLOW_PORT}:${MLFLOW_PORT}"
    environment:
      MLFLOW_PORT: ${MLFLOW_PORT}
      MLFLOW_S3_ENDPOINT_URL: http://minio:${S3_PORT}
      MLFLOW_BACKEND_STORE_URI: mysql+pymysql://${MYSQL_USER}:${MYSQL_USER_PASSWORD}@mysql/${MLFLOW_DATABASE}
      AWS_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
    depends_on:
      - mysql
      - minio

  dagster:
    build:
      context: .
      dockerfile: src/dagster/Dockerfile
    ports:
      - ${DAGSTER_PORT}:${DAGSTER_PORT}
    environment:
      - S3_PORT=${S3_PORT}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - BUCKET_NAME=${BUCKET_NAME}
      - INFLUX_PORT=8086
      - INFLUX_ORG=${INFLUX_ORG}
      - INFLUX_DATABASE=${INFLUX_DATABASE}
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_USER_PASSWORD=${MYSQL_USER_PASSWORD}
      - DAGSTER_DATABASE=${DAGSTER_DATABASE}
      - DAGSTER_PORT=${DAGSTER_PORT}
      - MLFLOW_PORT=${MLFLOW_PORT}
      - MLFLOW_S3_ENDPOINT_URL=http://minio:${S3_PORT}
      - MLFLOW_ARTIFACT_ROOT=s3://${BUCKET_NAME}/mlflow
      - HOST=${HOST}
      - MINIO_UI_PORT=${MINIO_UI_PORT}
    depends_on:
      - mysql
      - minio
      - mlflow

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
      DAGSTER_DATABASE: ${DAGSTER_DATABASE}
      MLFLOW_DATABASE: ${MLFLOW_DATABASE}
      CONFIG_DATABASE: ${CONFIG_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/mysql/init_databases.sh:/docker-entrypoint-initdb.d/init_databases.sh

  minio:
    image: minio/minio:latest
    ports:
      - ${S3_PORT}:${S3_PORT}
      - ${MINIO_UI_PORT}:${MINIO_UI_PORT}
    environment:
      MINIO_ACCESS_KEY: ${S3_ACCESS_KEY_ID}
      MINIO_SECRET_KEY: ${S3_SECRET_ACCESS_KEY}
    command: server /data --console-address :${MINIO_UI_PORT}
    volumes:
      - minio_data:/data

  influxdb:
    image: influxdb:latest
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUX_ADMIN_USER}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUX_ADMIN_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUX_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUX_DATABASE}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUX_TOKEN}
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2


volumes:
  log_data:
  grafana_data:
  mysql_data:
  minio_data:
  influxdb_data:
  influxdb_config:
