{
 "title": "Compare Measurements",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Deployment", "query": { "query": "SHOW MEASUREMENTS" } },
   { "name": "Compare", "label": "Compare to", "query": { "query": "SHOW MEASUREMENTS" } }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sensor Value",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "alias": "$Deployment",
     "measurement": "/^$Deployment$/",
     "query": "SELECT \"sensor_value\" FROM /^$Deployment$/ WHERE $timeFilter",
     "select": [
      [
       { "params": [ "sensor_value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "$Compare",
     "measurement": "/^$Compare$/",
     "query": "SELECT \"sensor_value\" FROM /^$Compare$/ WHERE $timeFilter AND \"$Deployment\" != \"$Compare\"",
     "select": [
      [
       { "params": [ "sensor_value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Model Name",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 1 },
   "targets": [
    {
     "alias": " ",
     "measurement": "/^$Deployment$/",
     "query": "SELECT first(\"model_name\") FROM /^$Deployment$/ WHERE $timeFilter",
     "select": [
      [
       { "params": [ "model_name" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ]
    },
    {
     "alias": " ",
     "measurement": "/^$Compare$/",
     "query": "SELECT first(\"model_name\") FROM /^$Deployment$/ WHERE $timeFilter",
     "select": [
      [
       { "params": [ "model_name" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Model Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 5 },
   "targets": [
    {
     "alias": " ",
     "measurement": "/^$Deployment$/",
     "select": [
      [
       { "params": [ "model_version" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ]
    },
    {
     "alias": " ",
     "measurement": "/^$Compare$/",
     "select": [
      [
       { "params": [ "model_version" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Predictions",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "alias": "$Deployment",
     "measurement": "/^$Deployment$/",
     "select": [
      [
       { "params": [ "prediction" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "$Compare",
     "measurement": "/^$Compare$/",
     "select": [
      [
       { "params": [ "prediction" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Data Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 9 },
   "targets": [
    {
     "alias": " ",
     "measurement": "/^$Deployment$/",
     "select": [
      [
       { "params": [ "model_name" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": " ",
     "measurement": "/^$Compare$/",
     "select": [
      [
       { "params": [ "model_name" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Colors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Red Mean",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "alias": "$Deployment",
     "measurement": "/^$Deployment$/",
     "query": "SELECT \"sensor_value\" FROM /^$Deployment$/ WHERE $timeFilter",
     "select": [
      [
       { "params": [ "red_mean" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "$Compare",
     "measurement": "/^$Compare$/",
     "query": "SELECT \"sensor_value\" FROM /^$Compare$/ WHERE $timeFilter AND \"$Deployment\" != \"$Compare\"",
     "select": [
      [
       { "params": [ "red_mean" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Green Mean",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "alias": "$Deployment",
     "measurement": "/^$Deployment$/",
     "query": "SELECT \"sensor_value\" FROM /^$Deployment$/ WHERE $timeFilter",
     "select": [
      [
       { "params": [ "green_mean" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "$Compare",
     "measurement": "/^$Compare$/",
     "query": "SELECT \"sensor_value\" FROM /^$Compare$/ WHERE $timeFilter AND \"$Deployment\" != \"$Compare\"",
     "select": [
      [
       { "params": [ "green_mean" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Blue Mean",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "alias": "$Deployment",
     "measurement": "/^$Deployment$/",
     "query": "SELECT \"sensor_value\" FROM /^$Deployment$/ WHERE $timeFilter",
     "select": [
      [
       { "params": [ "blue_mean" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "$Compare",
     "measurement": "/^$Compare$/",
     "query": "SELECT \"sensor_value\" FROM /^$Compare$/ WHERE $timeFilter AND \"$Deployment\" != \"$Compare\"",
     "select": [
      [
       { "params": [ "blue_mean" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Red Mean(Mean)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 20 },
   "targets": [
    {
     "alias": " ",
     "measurement": "/^$Deployment$/",
     "select": [
      [
       { "params": [ "red_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": " ",
     "measurement": "/^$Compare$/",
     "select": [
      [
       { "params": [ "red_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Red Mean(Mean)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 20 },
   "targets": [
    {
     "alias": " ",
     "measurement": "/^$Deployment$/",
     "select": [
      [
       { "params": [ "red_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": " ",
     "measurement": "/^$Compare$/",
     "select": [
      [
       { "params": [ "red_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Green Mean(Mean)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 20 },
   "targets": [
    {
     "alias": " ",
     "measurement": "/^$Deployment$/",
     "select": [
      [
       { "params": [ "green_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": " ",
     "measurement": "/^$Compare$/",
     "select": [
      [
       { "params": [ "green_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Green Mean(Std)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 20 },
   "targets": [
    {
     "alias": " ",
     "measurement": "/^$Deployment$/",
     "select": [
      [
       { "params": [ "green_std" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": " ",
     "measurement": "/^$Compare$/",
     "select": [
      [
       { "params": [ "green_std" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Blue Mean(Mean)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 20 },
   "targets": [
    {
     "alias": " ",
     "measurement": "/^$Deployment$/",
     "select": [
      [
       { "params": [ "blue_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": " ",
     "measurement": "/^$Compare$/",
     "select": [
      [
       { "params": [ "blue_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Blue Mean(Std)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 20 },
   "targets": [
    {
     "alias": " ",
     "measurement": "/^$Deployment$/",
     "select": [
      [
       { "params": [ "blue_std" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": " ",
     "measurement": "/^$Compare$/",
     "select": [
      [
       { "params": [ "blue_std" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Brightness Mean(Mean)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 23 },
   "targets": [
    {
     "alias": " ",
     "measurement": "/^$Deployment$/",
     "select": [
      [
       { "params": [ "brightness_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": " ",
     "measurement": "/^$Compare$/",
     "select": [
      [
       { "params": [ "brightness_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Brightness Mean(Mean)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 23 },
   "targets": [
    {
     "alias": " ",
     "measurement": "/^$Deployment$/",
     "select": [
      [
       { "params": [ "brightness_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": " ",
     "measurement": "/^$Compare$/",
     "select": [
      [
       { "params": [ "brightness_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hue mean(mean)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 23 },
   "targets": [
    {
     "alias": " ",
     "measurement": "/^$Deployment$/",
     "select": [
      [
       { "params": [ "hsv_H" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": " ",
     "measurement": "/^$Compare$/",
     "select": [
      [
       { "params": [ "hsv_H" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Saturation mean(mean)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 23 },
   "targets": [
    {
     "alias": " ",
     "measurement": "/^$Deployment$/",
     "select": [
      [
       { "params": [ "hsv_S" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": " ",
     "measurement": "/^$Compare$/",
     "select": [
      [
       { "params": [ "hsv_S" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Value mean(mean)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 23 },
   "targets": [
    {
     "alias": " ",
     "measurement": "/^$Deployment$/",
     "select": [
      [
       { "params": [ "hsv_V" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": " ",
     "measurement": "/^$Compare$/",
     "select": [
      [
       { "params": [ "hsv_V" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Tetures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Edge Count Mean",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 27 },
   "targets": [
    {
     "alias": " ",
     "measurement": "/^$Deployment$/",
     "select": [
      [
       { "params": [ "edge_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": " ",
     "measurement": "/^$Compare$/",
     "select": [
      [
       { "params": [ "edge_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Edge Count",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 27 },
   "targets": [
    {
     "alias": "$Deployment",
     "measurement": "/^$Deployment$/",
     "query": "SELECT \"sensor_value\" FROM /^$Deployment$/ WHERE $timeFilter",
     "select": [
      [
       { "params": [ "edge_count" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "$Compare",
     "measurement": "/^$Compare$/",
     "query": "SELECT \"sensor_value\" FROM /^$Compare$/ WHERE $timeFilter AND \"$Deployment\" != \"$Compare\"",
     "select": [
      [
       { "params": [ "edge_count" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Edge Count Std",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 30 },
   "targets": [
    {
     "alias": " ",
     "measurement": "/^$Deployment$/",
     "select": [
      [
       { "params": [ "edge_count" ], "type": "field" },
       {
        "params": [],
        "type": "stddev"
       }
      ]
     ]
    },
    {
     "alias": " ",
     "measurement": "/^$Compare$/",
     "select": [
      [
       { "params": [ "edge_count" ], "type": "field" },
       {
        "params": [],
        "type": "stddev"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Contrast",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 33 },
   "targets": [
    {
     "alias": " ",
     "measurement": "/^$Deployment$/",
     "select": [
      [
       { "params": [ "contrast" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": " ",
     "measurement": "/^$Compare$/",
     "select": [
      [
       { "params": [ "contrast" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dissimilarity",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 33 },
   "targets": [
    {
     "alias": " ",
     "measurement": "/^$Deployment$/",
     "select": [
      [
       { "params": [ "dissimilarity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": " ",
     "measurement": "/^$Compare$/",
     "select": [
      [
       { "params": [ "dissimilarity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Homogeneity",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 33 },
   "targets": [
    {
     "alias": " ",
     "measurement": "/^$Deployment$/",
     "select": [
      [
       { "params": [ "homogeneity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": " ",
     "measurement": "/^$Compare$/",
     "select": [
      [
       { "params": [ "homogeneity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Energy",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 33 },
   "targets": [
    {
     "alias": " ",
     "measurement": "/^$Deployment$/",
     "select": [
      [
       { "params": [ "energy" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": " ",
     "measurement": "/^$Compare$/",
     "select": [
      [
       { "params": [ "energy" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Features", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Keypoint Count",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "alias": "$Deployment",
     "measurement": "/^$Deployment$/",
     "query": "SELECT \"sensor_value\" FROM /^$Deployment$/ WHERE $timeFilter",
     "select": [
      [
       { "params": [ "keypoint_count" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "$Compare",
     "measurement": "/^$Compare$/",
     "query": "SELECT \"sensor_value\" FROM /^$Compare$/ WHERE $timeFilter AND \"$Deployment\" != \"$Compare\"",
     "select": [
      [
       { "params": [ "keypoint_count" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}