name: Model deployment

on:
  repository_dispatch:
    types: [deplay_model]

  workflow_dispatch:

jobs:
  test-model:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Print a message
      - name: Print a message
        run: echo "Testing the model..."

  deploy-model:
    environment: production
    needs: test-model
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Print a message
      - name: Print a message
        run: echo "Deploying the model..."