name: Model deployment

on:
  workflow_dispatch:
    inputs:
        name:
          description: 'The name of the model to deploy'
          required: true
        version:
          description: 'The version of the model to deploy'
          required: true
        environment:
          description: 'The environment to deploy to'
          required: true

jobs:
  test-model:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Print a message
      - name: Print a message
        run: echo "Testing the model..."

  deploy-model:
    environment: production
    needs: test-model
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Print a message
      - name: Print a message
        run: echo "Deploying the model..."