name: Model deployment to development

on:
  workflow_dispatch:
    inputs:
        name:
          description: 'The name of the model to deploy'
          required: true
        version:
          description: 'The version of the model to deploy'
          required: true

jobs:
  test-model:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Print a message
      - name: Print a message
        run: |
          echo "Testing the model: ${{ github.event.inputs.name }}"
          echo "Model version: ${{ github.event.inputs.version }}"

  deploy-to-development:
    environment: development
    needs: test-model
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Print a message
      - name: Print a message
        run: |
          echo "Deploying the model to development: ${{ github.event.inputs.name }}"
          echo "Model version: ${{ github.event.inputs.version }}"