name: Model training and evaluation

on:
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the Python script to train the model
      - name: Train the model
        run: |
          python src/train_model.py

      # Upload the trained model as an artifact
      - name: Upload Model Artifact
        uses: actions/upload-artifact@v3
        with:
          name: trained-model
          path: model.h5